#!/bin/sh

# check that the ILOM hostname or IP is provided
if [ -z $1 ]; then
	echo "Usage: ${0##*/} <ilom-hostname-or-IP>"
	exit 1
fi

# store the ILOM hostname or IP
ILOM=$1

# specify the folder to search for ISO files
ISO_FOLDER=${HOME}/public_html/mos_repo

cd ${ISO_FOLDER}
# display a list of found ISO files that are NOT ODA ISO files
PS3="Select ISO file [Ctrl-C to quit]: "
ISO_FILES=$(find . -name '*.iso' -and -not -name 'oda_bm_*.iso' -print | sort)
select ISO in ${ISO_FILES[@]}; do
	[ -z ${ISO} ] && exit 1
	ISO_PATH=$(realpath ${ISO})
	break
done

echo "ILOM: ${ILOM}"
echo "ISO: ${ISO_PATH}"

SSHFS_USER="software"
SSHFS_PASS="Welcome1"
SSHFS_URL="sshfs://10.187.101.25:${ISO_PATH}"
echo "SSHFS: ${SSHFS_URL}"

NFS_URL="nfs://10.187.101.25:${ISO_PATH}"
echo "NFS: ${NFS_URL}" 

# confirm
printf "Proceed? [YES or cancel]: "
read ACK

if [ "${ACK}" != "YES" ]; then
	echo "Cancelled."
	exit 1
fi

# USE THESE LINES FOR SSHFS
# set /SP/services/kvms/host_storage_device/remote server_uri=${SSHFS_URL}
# set /SP/services/kvms/host_storage_device/remote username=${SSHFS_USER}
# set /SP/services/kvms/host_storage_device/remote password
# ${SSHFS_PASS}
# ${SSHFS_PASS}


# THE POINT OF NO RETURN
# login to the ILOM
# power off the server
# configure the ILOM storage device redirect
# set the boot device to the remote boot device
# power on the server
echo "Enter password for root@${ILOM}:"
ssh -l root ${ILOM} << END_OF_INPUT

show /SYS
stop -f /SYS
y

show /SP/services/kvms/host_storage_device
show /SP/services/kvms/host_storage_device/remote

set /SP/services/kvms/host_storage_device mode=disabled
set /SP/services/kvms/host_storage_device/remote server_uri=${NFS_URL}

set /SP/services/kvms/host_storage_device mode=remote
set /HOST boot_device=cdrom

show /SP/services/kvms/host_storage_device/remote
show /SP/services/kvms/host_storage_device
show /HOST

start /SYS
y

END_OF_INPUT

echo "Server with ILOM ${ILOM} has been re-imaged."

